config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.http import HttpResponseRedirect

def redirect_root(request):
    return HttpResponseRedirect('/mytodo/')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mytodo/',include('mytodo.urls',namespace='mytodo')),
    path('',redirect_root),
]

mytodo/urls.py
from django.urls import path

from mytodo.views import list,detail,create,delete,update


app_name = 'mytodo'

urlpatterns = [
    path('',list.TaskListView.as_view(),name='task-list'),
    path('detail/<int:pk>/',detail.TaskDetailView.as_view(),name='task-detail'),
    path('create/',create.TaskCreateView.as_view(),name='task-create'),
    path('delete/<int:pk>/',delete.TaskDeleteView.as_view(),name='task-delete'),
    path('update/<int:pk>/',update.TaskUpdateView.as_view(),name='task-update'),
]

mytodo/models.py
from django.db import models

class Task(models.Model):
    doing = 0
    done = 1
    TASK_STATUS_CHOICES = (
        (0,'実行中'),
        (1,'完了')
    )
    title = models.CharField(max_length=50)
    body = models.TextField()
    status = models.IntegerField(default=0,choices=TASK_STATUS_CHOICES)

mytodo/views/create.py
from django.views.generic import CreateView
from django.urls import reverse_lazy

from mytodo.models import Task


class TaskCreateView(CreateView):
    model = Task
    fields = '__all__'
    initial = {'status':0}
    template_name = 'mytodo/create.html'
    success_url = reverse_lazy('mytodo:task-list')

mytodo/views/delete.py
from django.views.generic import DeleteView
from django.urls import reverse_lazy

from mytodo.models import Task


class TaskDeleteView(DeleteView):
    model = Task
    template_name = 'mytodo/delete.html'
    success_url = reverse_lazy('mytodo:task-list')

mytodo/views/detail.py
from django.views.generic import DetailView

from mytodo.models import Task


class TaskDetailView(DetailView):
    model = Task
    template_name = "mytodo/detail.html"

mytodo/views/list.py
from django.views.generic import ListView

from mytodo.models import Task

class TaskListView(ListView):
    model = Task
    template_name = 'mytodo/list.html'

mytodo/views/update.py
from django.views.generic import UpdateView
from django.urls import reverse_lazy

from mytodo.models import Task


class TaskUpdateView(UpdateView):
    model = Task
    fields = '__all__'
    template_name = 'mytodo/update.html'
    success_url = reverse_lazy('mytodo:task-list')

templates/mytodo/create.html
<form action="" method="post">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="Submit">
</form>

templates/mytodo/delete.html
<form action="" method="post">
  {% csrf_token %}
  <p><input type="submit" value="Yes"></p>
  <p><a href="{% url 'mytodo:task-list' %}">戻る</a></p>
</form>

templates/mytodo/detail.html
<h1>詳細</h1>
<div>タイトル:{{object.title}}</div>
<div>status:{{object.get_status_display}}</div>
<div>内容:{{object.body}}</div>
<p><a href="{% url 'mytodo:task-update' object.pk%}">編集</a></p>

templates/mytodo/list.html
<h1>リスト</h1>

<a href="create/"><p>新規追加</p></a>
<ul>
  {% for task in object_list %}
  {% if task.status != 0 %}
    <li><del><a href="detail/{{ task.id }}">{{ task.title }}</a>  </del>{{ task.get_status_display }} <a href="{% url 'mytodo:task-delete' task.pk %}">削除</a></li>
  {% else %}
    <li><a href="detail/{{ task.id }}">{{ task.title }}</a>  {{ task.get_status_display }} <a href="{% url 'mytodo:task-delete' task.pk %}">削除</a></li>
  {% endif %}
  
  {% empty %}
    <li>No tasks</li>
  {% endfor %}
</ul>

templates/mytodo/update.html
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p}}
  <input type="submit" value="Submit">
</form>